'use client';
import { useEffect, useRef, useState } from 'react';
import { ArrowUpRight, ArrowRight, Check, ChevronDown, Download, X, Menu, Sparkles, Compass, Orbit, ShieldCheck, Plus, Minus } from 'lucide-react';
import { focuses, plans, themes, reduceNumber, calendarText, downloadFile } from '../lib/planning';

function Mark({className=''}:{className?:string}) {return <svg className={className} width="35" height="35" viewBox="0 0 40 40" fill="none" aria-hidden="true"><circle cx="20" cy="20" r="16" stroke="currentColor" strokeWidth=".8"/><path d="M20 1v38M1 20h38M7 7l26 26M7 33L33 7" stroke="currentColor" strokeWidth=".6"/><path d="m20 7 3.2 9.8L33 20l-9.8 3.2L20 33l-3.2-9.8L7 20l9.8-3.2L20 7Z" fill="currentColor"/><circle cx="20" cy="20" r="3" fill="var(--ink)"/></svg>;}

const questions = [
  ['Is this a prediction of my future?', 'No. Astrology and numerology are interpretive traditions, not scientifically validated ways to predict events. Use these reports as prompts for reflection and planning. Your circumstances, evidence, and judgment should guide your decisions.'],
  ['How are astrology and numerology combined?', 'The integrated report is designed to show each method separately, explain where the interpretations converge or differ, and translate those themes into practical prompts. Assumptions and calculation methods will be stated rather than hidden.'],
  ['What if I don’t know my exact birth time?', 'The free numerology snapshot only needs your date of birth. Astrology interpretations can depend on precise time and place. If those details are uncertain, the report needs to state that limitation instead of inventing precision.'],
  ['Can I order a report right now?', 'Paid reports are coming soon. The displayed prices describe our planned offers. Checkout is not open, and no payment is collected on this site. You can use the free snapshot and download the sample planning calendar now.'],
  ['What happens to my birth details?', 'The free snapshot calculates entirely in your browser. Your date of birth is not sent to a server or saved by this page. You can choose to download your result. Ordering, delivery, and contact collection will need a separate consent process when they become available.'],
];

export default function Home(){
  const [focus,setFocus]=useState(0),[week,setWeek]=useState(0),[menuOpen,setMenuOpen]=useState(false),[modal,setModal]=useState<string|null>(null);
  const [dob,setDob]=useState(''),[error,setError]=useState(''),[downloaded,setDownloaded]=useState(false);
  const [snapshot,setSnapshot]=useState<{birth:ReturnType<typeof reduceNumber>;path:ReturnType<typeof reduceNumber>}|null>(null);
  const dialog=useRef<HTMLDialogElement>(null),hero=useRef<HTMLElement>(null),calendar=useRef<HTMLElement>(null);
  const [ready,setReady]=useState(false);
  const manualWeek=useRef(false);
  const chooseWeek=(value:number)=>{manualWeek.current=true;setWeek(value);};
  const plan=plans[focus][week];
  useEffect(()=>{const d=dialog.current;if(modal&&d&&!d.open)d.showModal();else if(!modal&&d?.open)d.close();},[modal]);
  useEffect(()=>{
    setReady(true);
    const reduced=matchMedia('(prefers-reduced-motion: reduce)'),fine=matchMedia('(hover: hover) and (pointer: fine)');let frame=0;
    const update=()=>{if(!reduced.matches&&hero.current)hero.current.style.setProperty('--hero-p',String(Math.max(0,Math.min(scrollY/800,1))));if(!reduced.matches&&calendar.current&&innerWidth>800){const r=calendar.current.getBoundingClientRect(),travel=r.height-innerHeight;if(r.top>innerHeight||r.bottom<0)manualWeek.current=false;if(!manualWeek.current&&r.top<0&&r.bottom>innerHeight&&travel>0)setWeek(Math.min(3,Math.floor((-r.top/travel)*4)));}frame=0;};
    const scroll=()=>{if(!frame)frame=requestAnimationFrame(update);};
    const pointer=(e:PointerEvent)=>{if(!hero.current||reduced.matches||!fine.matches)return;const r=hero.current.getBoundingClientRect();hero.current.style.setProperty('--mx',String((e.clientX/innerWidth-.5)*2));hero.current.style.setProperty('--my',String(((e.clientY-r.top)/r.height-.5)*2));};
    addEventListener('scroll',scroll,{passive:true});const h=hero.current;h?.addEventListener('pointermove',pointer);
    const script=document.createElement('script');script.src='/scrollcraft.js';script.onload=()=>{const w=window as unknown as {ScrollCraft?:{mount:(root:HTMLElement)=>void}};w.ScrollCraft?.mount(document.body);};document.body.appendChild(script);
    return()=>{removeEventListener('scroll',scroll);h?.removeEventListener('pointermove',pointer);cancelAnimationFrame(frame);script.remove();};
  },[]);
  function calculate(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const date=new Date(dob+'T00:00:00');if(!dob||isNaN(date.getTime())||date>new Date()||date.getFullYear()<1900){setError('Please enter a valid date of birth between 1900 and today.');setSnapshot(null);return;}setError('');setTimeout(()=>document.getElementById('snapshot-result-heading')?.focus(),100);setSnapshot({birth:reduceNumber(dob.slice(-2)),path:reduceNumber(dob.replaceAll('-',''))});}
  const closeMenu=()=>setMenuOpen(false);
  return <>
  <a className="skip-link" href="#main">Skip to content</a>
  <header className="header wrap"><a className="wordmark" href="#" aria-label="AnkDisha home"><Mark/><span>AnkDisha<span className="wordmark-dot">.</span></span></a><nav className={menuOpen?'navigation is-open':'navigation'} aria-label="Main navigation"><a href="#approach" onClick={closeMenu}>Our approach</a><a href="#calendar" onClick={closeMenu}>Inside your report</a><a href="#reports" onClick={closeMenu}>The reports</a><a className="mobile-nav-snapshot" href="#snapshot" onClick={closeMenu}>Free snapshot <ArrowUpRight size={16}/></a></nav><a className="button button-outline header-cta" href="#snapshot">Free snapshot <ArrowUpRight size={16}/></a><button className="menu-button icon-button" aria-label={menuOpen?'Close menu':'Open menu'} aria-expanded={menuOpen} onClick={()=>setMenuOpen(!menuOpen)}>{menuOpen?<X/>:<Menu/>}</button></header>
  <main id="main">
    <section className="hero wrap" ref={hero} data-sc-act="flow"><div className="hero-copy"><div className="eyebrow"><span className="tiny-star">✦</span> A LITTLE PERSPECTIVE. A CLEARER PATH.</div><h1>Your birth data.<br/><em>A clearer next step.</em></h1><p>Astrology and numerology, thoughtfully brought together.<br className="desktop-break"/> For the decisions that matter to you.</p><div className="hero-actions"><a href="#reports" className="button button-gold">Explore reports <ArrowUpRight size={18}/></a><a href="#calendar" className="text-link">Take a look inside <ArrowRight size={17}/></a></div></div><div className="hero-art" aria-hidden="true"><div className="star-field"><i/><i/><i/><i/><i/><i/><i/><i/></div><svg className="orbital-back" viewBox="0 0 640 640" fill="none"><circle cx="320" cy="320" r="285"/><circle cx="320" cy="320" r="298" strokeDasharray="1 12"/><path d="M20 320h600M320 20v600" strokeDasharray="2 8"/><circle cx="320" cy="35" r="3" fill="currentColor"/></svg><img className="armillary" src="/images/armillary.webp" width="1254" height="1254" alt="" fetchPriority="high"/><svg className="orbital-front" viewBox="0 0 640 640" fill="none"><ellipse cx="320" cy="320" rx="308" ry="112" transform="rotate(-31 320 320)"/><path d="m573 165 3 10 10 3-10 3-3 10-3-10-10-3 10-3Z" fill="currentColor"/><circle cx="59" cy="449" r="4" fill="currentColor"/></svg><span className="orbit-label label-one">PERSPECTIVE</span><span className="orbit-label label-two">POSSIBILITY</span></div></section>
    <div className="trust-strip wrap"><span><Orbit/> Two traditions, one thoughtful view</span><span><Compass/> Guidance you can put into practice</span><span><ShieldCheck/> Your decisions stay yours</span></div>
    <section className="approach wrap" id="approach" data-sc-act="flow"><div className="approach-heading" data-sc-in><span className="section-symbol" aria-hidden="true">✳</span><h2>Life isn’t a prediction.<br/>It’s a series of <em>possibilities.</em></h2></div><div className="approach-text" data-sc-in><p>You don’t need another hundred pages about your future. You need a little perspective on what comes next.</p><p>We bring the patterns of astrology and numerology into a practical planning report. The calculations are open. The assumptions are clear. The next step is always yours.</p><a className="text-link" href="#method">Meet the method <ArrowUpRight size={17}/></a></div></section>
    <section className="calendar-scene" id="calendar" ref={calendar} data-sc-act="flow"><div className="calendar-sticky" data-sc-verify-state={`focus-${focus}-week-${week}`}><div className="calendar-content wrap"><div className="calendar-intro"><div className="eyebrow">FROM INSIGHT TO EVERYDAY ACTION</div><h2>A little direction.<br/><em>One week at a time.</em></h2><p>A clear focus. A thoughtful plan. Space to decide.<br/>Explore a little of what’s inside.</p></div><div className="focus-tabs" role="group" aria-label="Choose a sample focus">{focuses.map((f,i)=><button key={f} aria-pressed={focus===i} onClick={()=>{manualWeek.current=true;setFocus(i);setWeek(0);setDownloaded(false);}}>{f}<ArrowUpRight size={15}/></button>)}</div><div className="calendar-spread"><div className="calendar-sheet"><div className="sheet-top"><span><Mark/> YOUR DECISION CALENDAR</span><span>ILLUSTRATIVE SAMPLE</span></div><div className="month-heading"><h3>September <em>2026</em></h3><Orbit size={27}/></div><div className="month-grid weekdays" aria-hidden="true">{['M','T','W','T','F','S','S'].map((d,i)=><span key={i}>{d}</span>)}</div><div className="month-grid days"><span/>{Array.from({length:30},(_,i)=>i+1).map(day=>{const w=plans[focus].findIndex(p=>p.day===day);return w>=0?<button key={day} className={week===w?'key-day active':'key-day'} aria-label={`September ${day}: ${plans[focus][w].tag}`} aria-pressed={week===w} onClick={()=>chooseWeek(w)}>{day}<span/></button>:<span key={day}>{day}</span>;})}</div><div className="calendar-legend"><span><i/> A moment to pause & plan</span><span>4 weeks. One intention.</span></div></div><div className="weekly-note" aria-live="polite" aria-atomic="true"><div className="note-heading"><span>WEEK {week+1}<span className="note-dot"> · </span>{plan.day} SEPTEMBER</span><span className="note-tag">{plan.tag}</span></div><h3>{plan.title}</h3><span className="small-label">YOUR PRACTICAL NEXT STEP</span><p>{plan.action}</p><div className="reflection"><span className="small-label">A QUESTION TO SIT WITH</span><p>“{plan.reflection}”</p></div><div className="week-navigation" role="group" aria-label="Sample week">{[0,1,2,3].map(i=><button key={i} onClick={()=>chooseWeek(i)} aria-pressed={week===i} aria-label={`View week ${i+1}`} className={week===i?'selected':''}>0{i+1}</button>)}<span>Room for your own judgment.</span></div></div></div><div className="sample-footer"><p>A sample of the format, not a personal reading. Dates and guidance are illustrative.</p><button className="text-link" onClick={()=>{downloadFile(calendarText(focus),'ankdisha-sample-calendar.ics','text/calendar;charset=utf-8');setDownloaded(true);}}>{downloaded?'Download again':'Try the calendar download'} <Download size={16}/></button></div></div></div></section>
    <section className="reports wrap" id="reports" data-sc-act="flow"><div className="section-heading"><h2>Find your kind<br/>of <em>clarity.</em></h2><p>A focused starting point or a fuller picture.<br/>Choose the perspective you’re looking for.</p></div><div className="report-collection" data-sc-reveal="up" data-sc-reveal-at="0.02 0.2"><div className="flagship"><div className="flagship-top"><span className="eyebrow">THE COMPLETE PICTURE</span><span className="mini-orbit" aria-hidden="true"><Orbit/></span></div><h3>Integrated<br/><em>Decision Calendar</em></h3><p>Two traditions. One defined goal.<br/>A practical, week-by-week way forward.</p><div className="price">₹1,499 <span>/ personal report</span></div><ul><li><Check/> Astrology + numerology, brought together</li><li><Check/> Clear calculations and stated assumptions</li><li><Check/> Weekly actions and 3–5 key dates</li><li><Check/> Calendar reminders + one-page summary</li></ul><div className="report-bottom"><button className="button button-gold" onClick={()=>setModal('Integrated Decision Calendar')}>Explore this report <ArrowUpRight size={18}/></button><span>20–35 thoughtful pages</span></div></div><div className="entry-reports"><article className="entry-report"><div className="entry-heading"><span className="report-icon"><Sparkles/></span><span className="page-count">6–10 PAGES</span></div><h3>Core Numerology</h3><p>Understand your birth numbers, name patterns, and the themes you can reflect on.</p><div className="entry-meta">Moolank · Bhagyank · Name number · Lo Shu</div><div className="entry-bottom"><span className="price">₹499</span><button className="circle-link" aria-label="Explore Core Numerology report" onClick={()=>setModal('Core Numerology')}><ArrowUpRight/></button></div></article><article className="entry-report"><div className="entry-heading"><span className="report-icon"><Orbit/></span><span className="page-count">20–30 PAGES</span></div><h3>Year-Ahead Astrology</h3><p>Take a wider view of the year, with monthly themes and practical preparation prompts.</p><div className="entry-meta">Annual overview · Monthly guidance · Key periods</div><div className="entry-bottom"><span className="price">₹699</span><button className="circle-link" aria-label="Explore Year-Ahead Astrology report" onClick={()=>setModal('Year-Ahead Astrology')}><ArrowUpRight/></button></div></article></div></div><p className="launch-note"><span/> Our first chapter is taking shape. Paid reports are coming soon. Explore the free snapshot today.</p></section>
    <section className="method" id="method" data-sc-act="flow"><div className="wrap method-grid"><div className="method-intro"><span className="eyebrow">THOUGHTFUL BY DESIGN</span><h2>A little tradition.<br/>A lot of <em>transparency.</em></h2><p>No hidden calculations. No guaranteed outcomes. Just an open process you can understand.</p></div><div className="method-steps"><article><span>01</span><div><h3>Start with what matters.</h3><p>Your birth details and one real question give the report its focus.</p></div></article><article><span>02</span><div><h3>See how we got there.</h3><p>Astrology and numerology sit side by side. Where they align, and where they differ, is explained.</p></div></article><article><span>03</span><div><h3>Leave with a next step.</h3><p>Short interpretations become preparation, reflection, and actions you can bring into your week.</p></div></article></div></div></section>
    <section className="faq wrap" id="questions" data-sc-act="flow"><div><h2>A few things<br/>you might be <em>wondering.</em></h2><p>Clarity starts with the right questions.</p></div><div className="faq-list">{questions.map(([q,a])=><details key={q}><summary>{q}<Plus className="faq-plus" size={19}/><Minus className="faq-minus" size={19}/></summary><p>{a}</p></details>)}</div></section>
    <section className="snapshot-section" id="snapshot" data-sc-act="flow"><div className="wrap snapshot-grid"><div className="snapshot-copy"><Mark className="snapshot-mark"/><div className="eyebrow">YOUR FIRST LITTLE INSIGHT</div><h2>Every journey starts<br/>with <em>a number.</em></h2><p>Find your birth number and life-path number.<br/>A simple calculation. A moment of reflection.</p><span className="privacy-line"><ShieldCheck size={15}/> Free. Private. No email needed.</span></div><div className="snapshot-tool"><form onSubmit={calculate} noValidate method="post"><label htmlFor="birth-date">Your date of birth</label><div className="date-input-row"><input id="birth-date" name="date-of-birth" type="date" disabled={!ready} min="1900-01-01" value={dob} onChange={e=>{setDob(e.target.value);setSnapshot(null);setError('');}} aria-describedby={error?'date-error':'date-hint'} aria-invalid={!!error} required/><button className="button button-gold" type="submit" disabled={!ready}>Find my numbers <ArrowRight size={18}/></button></div><p id="date-hint">Calculated on your device. Your birth details stay with you.</p>{error&&<p id="date-error" className="form-error" role="alert">{error}</p>}</form>{snapshot?<div className="snapshot-result" aria-live="polite"><div className="result-numbers"><div><strong>{snapshot.birth.number}</strong><span>Birth number · Moolank</span></div><div><strong>{snapshot.path.number}</strong><span>Life path · Bhagyank</span></div></div><h3 id="snapshot-result-heading" tabIndex={-1}>A prompt for {themes[snapshot.birth.number].title}.</h3><p>{themes[snapshot.birth.number].prompt}</p><details className="calculation-details"><summary>See the calculation <ChevronDown size={16}/></summary><p>Birth number: {snapshot.birth.calculation}</p><p>Life path: {snapshot.path.calculation}</p><p>Method: reduce to 1–9, including master numbers. Other traditions use different conventions. Themes are traditional associations, not assessments of your personality.</p></details><button className="text-link" onClick={()=>downloadFile(`ANKDISHA | PERSONAL NUMBER SNAPSHOT\n\nBirth number: ${snapshot.birth.number}\n${snapshot.birth.calculation}\n\nLife-path number: ${snapshot.path.number}\n${snapshot.path.calculation}\n\nReflection: ${themes[snapshot.birth.number].prompt}\n\nMethod: reduce all digits to 1-9. Traditional associations for reflection, not predictions or a personality assessment.\nGenerated locally. No birth details were sent to a server.`,'ankdisha-my-snapshot.txt','text/plain;charset=utf-8')}>Keep my snapshot <Download size={15}/></button></div>:<div className="snapshot-empty"><span aria-hidden="true">1 <i>·</i> 2 <i>·</i> 3 <i>·</i> 4 <i>·</i> 5 <i>·</i> 6 <i>·</i> 7 <i>·</i> 8 <i>·</i> 9</span><p>A small starting point, with the workings included.</p></div>}<noscript><p>The private calculator needs JavaScript. No birth details will be placed in a URL by this form.</p></noscript></div></div></section>
  </main>
  <footer className="footer wrap"><div className="footer-top"><a className="wordmark" href="#"><Mark/><span>AnkDisha<span className="wordmark-dot">.</span></span></a><p>Rooted in tradition. Grounded in possibility.</p><a className="text-link" href="#">Back to the beginning <ArrowUpRight size={16}/></a></div><div className="footer-bottom"><span>© 2026 AnkDisha. Your direction is yours.</span><div><button onClick={()=>setModal('Privacy')}>Privacy</button><button onClick={()=>setModal('Delivery & refunds')}>Delivery & refunds</button><button onClick={()=>setModal('A note on guidance')}>A note on guidance</button></div></div></footer>
  <dialog ref={dialog} className="detail-dialog" aria-labelledby="dialog-title" onCancel={()=>setModal(null)} onClick={e=>{if(e.target===dialog.current)setModal(null);}}><button className="dialog-close icon-button" aria-label="Close dialog" onClick={()=>setModal(null)}><X/></button><Mark/><h2 id="dialog-title">{modal}</h2>{modal==='Privacy'?<><p>The free snapshot runs in your browser. This page does not transmit, store, or share the date you enter. Downloaded snapshots are saved to your device only when you request them.</p><p>This preview has no advertising trackers, newsletter signup, or payment collection. The hosting service may process normal access logs. A full ordering privacy notice will be provided before paid orders open.</p></>:modal==='Delivery & refunds'?<><p>Paid reports are not yet available to order. No payment is collected and no report delivery is promised by this preview.</p><p>Final turnaround times, payment terms, cancellation, and refund details will be displayed before checkout opens. Sample calendar and number-snapshot downloads are available immediately and free.</p></>:modal==='A note on guidance'?<><p>Astrology and numerology are interpretive traditions and are not scientifically validated predictors of future events. This experience is intended for reflection and general planning.</p><p>It does not replace qualified medical, legal, or financial advice. Sample calendar dates are illustrative and are not auspicious-date calculations. No particular outcome is promised.</p></>:<><span className="availability">COMING SOON</span><p>{modal==='Integrated Decision Calendar'?'Our planned flagship brings astrology and numerology together around one goal, with open assumptions, weekly actions, and downloadable calendar reminders.':modal==='Core Numerology'?'A focused introduction to Moolank, Bhagyank, name-number and Lo Shu traditions, with calculations and practical reflection prompts.':'An annual and monthly perspective using astrology, with clearly stated assumptions and practical prompts for the year ahead.'}</p><p>We’re preparing our first reports. Checkout is not open yet. Start with the free number snapshot or explore the sample calendar.</p><a className="button button-gold" href="#snapshot" onClick={()=>setModal(null)}>Try the free snapshot <ArrowUpRight size={18}/></a></>}</dialog>
  </>;
}
